---

- name: Download Helm
  when: master is defined
  get_url:
    url: https://storage.googleapis.com/kubernetes-helm/helm-{{ helm_version }}-linux-{{ helm_arch }}.tar.gz
    dest: /tmp/helm.tar.gz
    mode: 0440
  tags: [helm]

- name: Extract Helm into /tmp
  when: master is defined
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/
  tags: [helm]

- name: Copy Helm Binary into /usr/local/bin/
  when: master is defined
  copy:
    src: /tmp/linux-{{ helm_arch }}/helm
    dest: /usr/local/bin/helm
    owner: "root"
    group: "root"
    mode: 0744
  tags: [helm]

- name: Initialize Helm
  when: master is defined
  shell: helm init #--home /home/{{ app_user }}/.helm/
  tags: [helm]

- name: Initialize RBAC for helm
  when: master is defined
  shell: kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
  tags: [helm]

- name: update Helm repos
  when: master is defined
  shell: helm repo update
  tags: [helm]