---

- name: Ensure to pass bridged IPv4 traffic to iptables chains
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Ensure depdencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Google GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Ensure Kubernetes repo is available
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ {{ kube_channel }} main'
    filename: kubernetes
    state: present

- name: apt-get clean
  command: apt-get clean

- name: apt-get update
  command: apt-get update

- name: Installing Kubelets and Kubeadm
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet={{ kubelet_version }}
    - kubeadm={{ kubeadm_version }}

#- name: Installing Kubectl on Master Node
#  apt:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - kubectl
#  when: inventory_hostname in groups['master']

- name: Ensure to replace bashrc for $app_user
  when: inventory_hostname in groups['master']
  copy:
    src: /root/.bashrc
    dest: /home/{{ app_user }}/.bashrc
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0744
    
- name: Ensure Kubelet Unitfile is setup with cgroup defined
  template:
    src: roles/kubeadm/templates/kubeadm.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure systemd is reloaded
  systemd: daemon_reload=yes

- name: Ensure kubelet has restarted
  systemd:
    state: restarted
    name: kubelet

- name: Ensure Kubernetes master is set to defaultvalues
  shell: "kubeadm reset"

- name: Init Kubernetes cluster
  when: inventory_hostname in groups['master']
  shell: kubeadm init --kubernetes-version {{ kube_version }} --apiserver-advertise-address {{ ip }} --token {{ kube_token }} --pod-network-cidr={{ pod_network_cidr }}

- name: Ensure to create the Kubernetes configdirectory for $app_user
  file: path=/home/{{ app_user }}/.kube/ state=directory
  when: inventory_hostname in groups['master']

- name: Copy admin.conf to /home/{{ app_user }}/.kube directory
  when: inventory_hostname in groups['master']
  copy:
    src: "{{ kubectl_config }}"
    dest: "/home/{{ app_user }}/.kube/config"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0744

- name: Ensure to create the Kubernetes configdirectory for root
  file: path=/root/.kube/ state=directory
  when: inventory_hostname in groups['master']

- name: Copy admin.conf to /root/.kube directory
  when: inventory_hostname in groups['master']
  copy:
    src: "{{ kubectl_config }}"
    dest: "/root/.kube/config"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0744

- name: Ensure Kubernetes nodes are set to defaultvalues
  when: inventory_hostname in groups['nodes']
  shell: "kubeadm reset"

- name: Ensure nodes are connected to the Kubernetes API
  when: inventory_hostname in groups['nodes']
  shell: kubeadm join --token {{ kube_token }} {{ kube_master_ip }}:6443 --discovery-token-unsafe-skip-ca-verification

- name: insert/update "Match User" configuration block in /etc/ssh/sshd_config
  blockinfile:
    path: /home/{{ app_user }}/.bashrc
    block: |
      source <(kubectl completion bash)
      function k-sys() {
        alias k="kubectl --namespace kube-system"
        printf "\n${red}kubectl --namespace kube-system active\n\n${reset}"
      }
      function k-pub() {
        alias k="kubectl --namespace kube-public"
        printf "\n${green}kubectl --namespace kube-public active\n\n${reset}"
      }
      function k-def() {
        alias k="kubectl"
        printf "\n${green}kubectl without namespace active\n\n${reset}"
      }
      function k-nodes() {
        for i in kube-{1..3}; do
          printf "${yellow}item: $i:${reset}\n"
          kubectl describe node $i.foo.io | grep -A4 "Allocated resources:"
        done
      }

- name: Start Flannel...
  when: inventory_hostname in groups['master']
  shell: "kubectl apply -f /vagrant/ansible/deployments/flannel.yml"


